%% optimizer.pl — SICStus Prolog CLP(FD) solver for Multi-Tenant Antenna Placement.
%%
%% Model summary
%% -------------
%% Given an R×C grid with four terrain types, place cell towers and assign
%% antennas from four telecom providers to minimise total infrastructure cost.
%%
%% Decision variables (all 0/1 domain):
%%   T        — tower list;  T[i] = 1 iff a tower is built at cell i
%%   P0..P3   — antenna lists; Pk[i] = 1 iff provider k has an antenna at cell i
%%   S0..S3   — slack lists;   Sk[j] = 1 iff cell j is NOT covered by provider k
%%
%% Constraints:
%%   C1  T[i] = 0                     for every banned (mountain) cell i
%%   C2  Pk[i] =< T[i]               antenna requires a tower
%%   C3  sum([P0[i]..P3[i]]) =< 4    at most 4 tenants per tower
%%   C4  sum(CoverageVars) + Sk[j] >= 1   cover cell j or activate the slack
%%
%% Objective (minimised via branch-and-bound labeling):
%%   GlobalCost = sum(c_i * T[i])          tower construction
%%              + 100 * sum(all antennas)   antenna slot fees
%%              + 800 * sum(all slacks)     uncoverage penalties
%%
%% Entry point:
%%   run_optimization(GlobalCost, CoveragePercentage)
%%
%% The map data (grid dimensions, provider radii, terrain cell indices) is
%% loaded from map_data.pl, generated by sicstus/preprocessor.py.

:- use_module(library(clpfd)).
:- use_module(library(lists)).
:- use_module(library(between)).

:- ensure_loaded('map_data.pl').


% =====================================================================
% COVERAGE GEOMETRY  (mirrors OR-Tools get_covered_cells)
%
% manhattan_covers(+K, +Src, +Tgt)
%   Succeeds iff an antenna of provider K at cell Src covers cell Tgt,
%   i.e. their Manhattan distance is within provider K's radius.
% =====================================================================
manhattan_covers(K, Src, Tgt) :-
    grid_dimensions(_, _, Cols),
    provider_radius(K, R),
    SrcRow is Src // Cols, SrcCol is Src mod Cols,
    TgtRow is Tgt // Cols, TgtCol is Tgt mod Cols,
    Dist is abs(SrcRow - TgtRow) + abs(SrcCol - TgtCol),
    Dist =< R.


% =====================================================================
% TERRAIN COST  (mirrors OR-Tools get_tower_base_cost)
%
% tower_base_cost(+CellIdx, -Cost)
%   Returns the terrain-dependent tower construction cost for CellIdx.
%   Building: €2500, Forest: €1500, Plains/other: €1000.
% =====================================================================
tower_base_cost(I, 2500) :- is_building(I), !.
tower_base_cost(I, 1500) :- is_forest(I), !.
tower_base_cost(_, 1000).

%% build_base_costs(+GridSize, -Costs)
%   Builds the list of tower base costs [c_0, c_1, ..., c_{N-1}]
%   used as coefficients in the scalar_product for tower cost.
build_base_costs(GridSize, Costs) :-
    GridSizeM1 is GridSize - 1,
    findall(C, (between(0, GridSizeM1, I), tower_base_cost(I, C)), Costs).


% =====================================================================
% 1. MAIN ENTRY POINT
%
% run_optimization(-GlobalCost, -CoveragePercentage)
%   Builds the CSP, runs branch-and-bound to find the minimum cost
%   placement, and returns the optimal cost and coverage percentage.
% =====================================================================
run_optimization(GlobalCost, CoveragePercentage) :-
    grid_dimensions(GridSize, _, _),
    AntennaCost = 100,   % €100 per antenna slot
    PenaltyCost = 800,   % €800 per uncovered (provider, cell) pair

    % --- Declare 0/1 domain variables ---
    % T:  tower variables — one per grid cell
    % P0..P3: antenna variables — one list per provider, one element per cell
    % S0..S3: slack variables  — one list per provider, one element per cell
    %         (Sk[j]=1 means cell j is not covered by provider k → penalty applies)
    length(T,  GridSize), domain(T,  0, 1),
    length(P0, GridSize), domain(P0, 0, 1),
    length(P1, GridSize), domain(P1, 0, 1),
    length(P2, GridSize), domain(P2, 0, 1),
    length(P3, GridSize), domain(P3, 0, 1),

    length(S0, GridSize), domain(S0, 0, 1),
    length(S1, GridSize), domain(S1, 0, 1),
    length(S2, GridSize), domain(S2, 0, 1),
    length(S3, GridSize), domain(S3, 0, 1),

    % STEP 1: Post topology constraints (C1, C2, C3) and coverage constraints (C4)
    constrain_topology(T, P0, P1, P2, P3, 0),
    constrain_coverage([P0, P1, P2, P3], [S0, S1, S2, S3], 0, 4, GridSize),

    % STEP 2: Build GlobalCost as a CLP(FD) expression for branch-and-bound
    build_base_costs(GridSize, BaseCosts),
    scalar_product(BaseCosts, T, #=, TowerCostVar),

    append([P0, P1, P2, P3], AllAnts),
    length(AllAnts, NAnts), length(AntCoeffs, NAnts),
    maplist(=(AntennaCost), AntCoeffs),
    scalar_product(AntCoeffs, AllAnts, #=, AntCostVar),

    append([S0, S1, S2, S3], AllSlacks),
    length(AllSlacks, NSlacks), length(PenCoeffs, NSlacks),
    maplist(=(PenaltyCost), PenCoeffs),
    scalar_product(PenCoeffs, AllSlacks, #=, PenaltyCostVar),

    GlobalCost #= TowerCostVar + AntCostVar + PenaltyCostVar,

    % STEP 3: Branch-and-bound search with first-fail variable ordering
    % ff: at each step, branch on the variable with the smallest remaining domain
    % minimize(GlobalCost): keep the incumbent and search for strictly cheaper solutions
    append([T, P0, P1, P2, P3, S0, S1, S2, S3], AllVars),
    labeling([ff, minimize(GlobalCost)], AllVars),

    % STEP 4: Compute coverage percentage once all variables are ground
    sumlist(S0, D0), sumlist(S1, D1), sumlist(S2, D2), sumlist(S3, D3),
    TotalDrops is D0 + D1 + D2 + D3,
    GridSizeM1 is GridSize - 1,
    findall(I, (between(0, GridSizeM1, I), \+ is_banned(I)), Coverable),
    length(Coverable, NumCoverable),
    TotalPoss is NumCoverable * 4,
    CoveragePercentage is ((TotalPoss - TotalDrops) * 100) // TotalPoss.


% =====================================================================
% 2. TOPOLOGY CONSTRAINTS  (C1 + C2 + C3)
%
% constrain_topology(+T, +P0, +P1, +P2, +P3, +CellIdx)
%   Walks all four antenna lists in parallel with the tower list and
%   posts per-cell constraints:
%     C1: T[i] = 0  if cell i is banned
%     C2: Pk[i] =< T[i]  for each provider k
%     C3: sum of antennas at cell i =< 4
% =====================================================================
constrain_topology([], [], [], [], [], _) :- !.
constrain_topology([Tower|Ts], [Ant0|A0s], [Ant1|A1s], [Ant2|A2s], [Ant3|A3s], I) :-
    % C1: mountains cannot host towers
    (is_banned(I) -> Tower #= 0 ; true),

    % C2: each antenna requires a tower at the same cell
    Ant0 #=< Tower,
    Ant1 #=< Tower,
    Ant2 #=< Tower,
    Ant3 #=< Tower,

    % C3: multi-tenant cap (at most 4 providers per tower)
    sum([Ant0, Ant1, Ant2, Ant3], #=<, 4),

    NextI is I + 1,
    constrain_topology(Ts, A0s, A1s, A2s, A3s, NextI).


% =====================================================================
% 3. COVERAGE CONSTRAINTS  (C4)
%
% constrain_coverage(+AntennaLists, +SlackLists, +K, +NumProv, +GridSize)
%   Iterates over providers 0..NumProv-1 and posts C4 for each:
%     sum_{i in cov(k,j)} Pk[i] + Sk[j] >= 1
%   i.e. cell j is covered by provider k, or the slack is 1 (penalty).
% =====================================================================
constrain_coverage(_, _, NumProv, NumProv, _) :- !.
constrain_coverage(Antennas, Slacks, K, NumProv, GridSize) :-
    nth0(K, Antennas, P_k),
    nth0(K, Slacks,   S_k),
    loop_target_cells(P_k, S_k, K, 0, GridSize),
    NextK is K + 1,
    constrain_coverage(Antennas, Slacks, NextK, NumProv, GridSize).

%% loop_target_cells(+P_k, +S_k, +K, +Tgt, +GridSize)
%   Posts C4 for provider K on every target cell 0..GridSize-1.
%   Banned cells get slack forced to 0 (no penalty, they are simply excluded).
%   Cells with no valid coverage sources get slack forced to 1 (always penalised).
loop_target_cells(_, [], _, _, _) :- !.
loop_target_cells(P_k, [SlackVar|RestSlacks], K, Tgt, GridSize) :-
    (is_banned(Tgt) ->
        % Banned cells are not coverable; no penalty is charged for them
        SlackVar #= 0
    ;
        % Find all non-banned source cells that can cover Tgt under provider K
        GridSizeM1 is GridSize - 1,
        findall(Src, (between(0, GridSizeM1, Src),
                      \+ is_banned(Src),
                      manhattan_covers(K, Src, Tgt)),
                ValidSources),
        extract_domain_vars(ValidSources, P_k, CoverageVars),
        (CoverageVars == [] ->
            % No source can cover this cell → always penalised
            SlackVar #= 1
        ;
            % C4: at least one covering antenna active, or slack = 1
            sum([SlackVar|CoverageVars], #>=, 1)
        )
    ),
    NextTgt is Tgt + 1,
    loop_target_cells(P_k, RestSlacks, K, NextTgt, GridSize).


% =====================================================================
% 4. UTILITY
%
% extract_domain_vars(+Indices, +VarList, -Vars)
%   Given a list of 0-based cell indices and a flat list of CLP(FD)
%   variables, extracts the variables at those positions.
%   Uses element/3 (1-based), so indices are shifted by +1.
% =====================================================================
extract_domain_vars([], _, []).
extract_domain_vars([Idx|Idxs], List, [Var|Vars]) :-
    PrologIdx is Idx + 1,          % element/3 uses 1-based indexing
    element(PrologIdx, List, Var),
    extract_domain_vars(Idxs, List, Vars).
