# preprocessor.py
import math

def generate_prolog_facts(map_string, provider_ranges, output_filename="map_data.pl"):
    lines = [line.strip().split() for line in map_string.strip().split('\n') if line.strip()]
    N = len(lines)
    M = len(lines[0]) if N > 0 else 0
    grid_size = N * M

    attenuation_costs = {'.': 0, 'F': 1, 'B': 2}
    
    with open(output_filename, "w") as f:
        f.write(f"%% Autogenerated Map Facts\n")
        f.write(f"grid_dimensions({grid_size}, {N}, {M}).\n\n")
        
        # Write banned infrastructure placement zones (Mountains 'X')
        for idx, line in enumerate(sum(lines, [])):
            if line == 'X':
                f.write(f"is_banned({idx}).\n")
        f.write("\n")

        # Compute attenuated visibility rays
        for k, max_budget in provider_ranges.items():
            for src in range(grid_size):
                src_r, src_c = src // M, src % M
                
                # Check if src is on a mountain (cannot place tower)
                if lines[src_r][src_c] == 'X':
                    continue
                    
                for tgt in range(grid_size):
                    if src == tgt:
                        f.write(f"can_cover({k}, {src}, {tgt}).\n")
                        continue
                        
                    tgt_r, tgt_c = tgt // M, tgt % M
                    steps = max(abs(tgt_r - src_r), abs(tgt_c - src_c))
                    signal_budget = max_budget
                    blocked = False
                    
                    for step in range(1, steps + 1):
                        curr_r = src_r + round(step * (tgt_r - src_r) / steps)
                        curr_c = src_c + round(step * (tgt_c - src_c) / steps)
                        
                        if not (0 <= curr_r < N and 0 <= curr_c < M):
                            blocked = True; break
                        
                        cell_type = lines[curr_r][curr_c]
                        if cell_type == 'X':
                            blocked = True; break
                        if cell_type in attenuation_costs:
                            signal_budget -= attenuation_costs[cell_type]
                            
                    if not blocked and signal_budget >= 0:
                        f.write(f"can_cover({k}, {src}, {tgt}).\n")
                        
    print(f"Successfully compiled terrain to {output_filename} ({grid_size} cells evaluated).")

if __name__ == "__main__":
    PORTO_MAP = """
    .  .  .  .  .  .
    .  B  B  .  F  .
    .  B  B  .  F  .
    X  X  .  .  .  .
    .  .  .  B  B  .
    .  .  .  B  B  .
    """
    # 4 distinct frequency bands matching Phase 3 specs
    generate_prolog_facts(PORTO_MAP, {0: 4, 1: 3, 2: 2, 3: 1})